# This is where I would store tokens needed to clone my applications

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: zsw36318
spec:
  encryptedData:
    TOKEN: AgB3S3td0vLlD0prfsng+LqLrTVS2ahxl6jJILa6gyUm7oZyOPsgiOnj40Q5rG/sPZPObgcsBXZB62Xw7JgWqfI4MAUqRQG8C+9nOFCrvFwv05MuKfP8Q/5kzFPNZv91vKILCkgdjI9WYx9P4XSZMlCtfY1M6ARlt6+yYzxxT/RTAZ/dgvTVLOdJ5ZA4QACvUWpayWCbhoexFlFC2HpuCH4EfMIRojVmigWx/REdpd2iMvVZquqiikhEO03uJ98eK3tFu7DdwXHKAqFIzAYEDGWli63JcxOaBc2vYT5dBJlxF+K2EBZkzFWDvqwofM0KCo50LEeoMwP092wYClAgld8QUYGV4wH3iIxfG3hOeO8YHAJdnR66TslB7hwt7KCbIt7qLG2a0BaDgh2wAQoSVOwa4Rn5aTTGrqjXIpvSTixLVrgTmiSnisgHvjZ0hV+Tc1+ml78xMHc6mMXtGnfXDL7RnMCj5PlBIOLoiZA/NUAeAr+aO+HILBOx++gYwhUxWXdF9eJBqGRD0SOAqRjl4omvjABxCJS3ZzmgYwQlp0TRWN5m1wxIH09SVD9JqKb6AZcJTOstTFmuy/h3XOWYFFfyv0Miug+gtgqGp9BxdZtWkTgQ9pg5xU6t7O2uhdWJmwiv88ctFG/YTY4TLGmSWKZRD7gzpcXoraX/Pwrm6yKA91QJ4PuApR7ClkeONGJqiuAzZJ5BUnZ4o7deqnbOFLIyo/08ciTHQCzYyJIjWRLioAjFamMme4HLTNNPrXt3kdWLyzGbdgn43kocuC2L6PJKQecha8nlwgRruarfok7tLGMoVBI2zOHRqp2cjvU=
  template:
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: zsw36318
