name: Build and Push Image

on:
  push:
    branches: [ dev-branch ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Log in to registry
        run: | 
          podman login ghcr.io -u $GITHUB_ACTOR --password "${{ secrets.CR_PAT }}"

      - name: Build image
        run: |
          IMAGE=ghcr.io/${{ github.repository }}:${{ github.sha }}
          podman build -t $IMAGE .

      - name: Push image
        run: |
          IMAGE=ghcr.io/${{ github.repository }}:${{ github.sha }}
          podnab push $IMAGE

      - name: Update image tag
        run: |
          sed -i "s|image: .*|image: ghcr.io/${{ github.repository }}:${{ github.sha }}|" \
            manifests/base/deployment.yaml